require "colorize"
require_relative "code_breaker"
require_relative "code_maker"
require_relative "game_board"
require_relative "human_code_maker"
require_relative "comp_code_breaker"

class Game
  def initialize()
    @game_board = GameBoard.new()
    @number_of_guesses = 0
    @player_role = "0"
    @feedback = ""
  end

  def evaluate_guess(guess, answer)
    feedback = []
    if check_win?(guess, answer)
      return ["1", "1", "1", "1"]
    end
    guess.each_with_index do |digit, index|
      if answer[index] == digit
        feedback << "1"
      elsif answer.include?(digit)
        if guess.count(digit) >= 2 
          next unless answer.count(digit) == guess.count(digit)
          feedback << "2"
        end
        feedback << "2"
      end
    end
    feedback.shuffle
  end

  def check_win?(guess, answer)
    guess == answer ? true : false
  end

  def play_round(answer)
    print_colours
    guess = @code_breaker.makeGuess(@feedback)
    @feedback = evaluate_guess(guess, answer)
    @number_of_guesses += 1
    @game_board.place_guess(@number_of_guesses, guess)
    @game_board.place_feedback(@number_of_guesses, @feedback)
    guess
  end
  
  def print_instructions
    puts "---------------------------------------"
    puts "Welcome to MASTERMIND"
    puts "---------------------------------------"
    puts "You can play as one of the following roles:"
    puts "[1] Code Maker: Create a secret code that the computer will attempt to decrypt.".colorize(:green)
    puts "[2] Code Maker: Decrypt the secret code generated by the computer.".colorize(:red)
    puts "---------------------------------------"
  end

  def print_maker_instructions
    puts "Your mission:"
    puts "Create a 4-digit secret code.".colorize(:green)
    puts "---------------------------------------"
    puts "START GAME"
    puts "---------------------------------------"
    print_colours
  end

  def print_breaker_instructions
    puts "Your mission:"
    puts "Decrypt the 4-digit sequence within 12 tries.".colorize(:red)
    puts "---------------------------------------"
    puts "To aid you in your mission, additional info for each guess will be provided in the form of key pegs:"
    print "\u25C9 ".colorize(:red)
    puts "RED PEG: Correct Colour + Correct Position"
    print "\u25C9 ".colorize(:white)
    puts "WHITE PEG: Correct Colour + Wrong Position"
    print "\u25CC "
    puts "EMPTY: No match found"
    puts "Note: The sequence of the provided feedback is shuffled."
    puts "---------------------------------------"
    puts "START GAME"
  end

  def print_colours
    print "Available colours:"
    print " \u278A".colorize(:red)
    print " \u2777".colorize(:green)
    print " \u2778".colorize(:yellow)
    print " \u2779".colorize(:blue)
    print " \u277A".colorize(:cyan)
    print " \u277B \n".colorize(:magenta)
  end

  def start_game
    print_instructions
    loop do 
      print "Choose your role - [1] or [2] : "
      @player_role = gets.chomp
      break if @player_role == "1" || @player_role == "2"
      puts "Invalid input: Please try again"
    end
    
    case @player_role
    when "1"
      @code_maker = HumanCodeMaker.new
      @code_breaker = ComputerCodeBreaker.new
      print_maker_instructions
    when "2"
      @code_maker = CodeMaker.new
      @code_breaker = CodeBreaker.new
      print_breaker_instructions
    end

    answer = @code_maker.generateCode

    loop do
      @game_board.print_board
      guess = play_round(answer)
      if check_win?(guess, answer)
        @game_board.print_board
        puts "Congratulations! The #{@code_breaker} has won the game!"
        break
      elsif @number_of_guesses == 12
        @game_board.print_board
        puts "The #{@code_breaker} has run out of guesses. The #{@code_maker} has won the game!"
        break
      end
    end

    puts "GAME OVER"
  end
end
