require "colorize"
require_relative "code_breaker"
require_relative "code_maker"
require_relative "game_board"
require_relative "human_code_maker"
require_relative "comp_code_breaker"

# A class that controls the logic and gameplay of the Mastermind game
class Game
  def initialize
    @game_board = GameBoard.new
    @number_of_guesses = 0
    @player_role = "0"
    @answer = []
    @feedback = ""
    @colours = { red: "\u278A", green: "\u2777", yellow: "\u2778", blue: "\u2779", cyan: "\u277A",
                 magenta: "\u277B" }
  end

  def evaluate_guess(guess)
    # Evaluate the guess made by the code breaker
    feedback = []
    return %w[1 1 1 1] if check_win?(guess)

    guess.each_with_index do |digit, index|
      # Add a red peg (1) if the guessed peg is in the correct position + correct colour
      if @answer[index] == digit
        feedback << "1"
      elsif @answer.include?(digit)
        # Add a white peg (2) if the guessed peg is in the wrong position + correct colour
        if guess.count(digit) >= 2
          next unless @answer.count(digit) == guess.count(digit)

          feedback << "2"
        end
        feedback << "2"
      end
    end
    feedback.shuffle
  end

  def check_win?(guess)
    guess == @answer
  end

  def play_round
    print_colours
    guess = @code_breaker.make_guess(@feedback)
    @feedback = evaluate_guess(guess)
    @number_of_guesses += 1
    @game_board.place_guess(@number_of_guesses, guess)
    @game_board.place_feedback(@number_of_guesses, @feedback)
    guess
  end

  def print_instructions
    puts "---------------------------------------"
    puts "Welcome to MASTERMIND"
    puts "---------------------------------------"
    puts "You can play as one of the following roles:"
    puts "[1] Code Maker: Create a secret code that the computer will attempt to decrypt.".colorize(:green)
    puts "[2] Code Maker: Decrypt the secret code generated by the computer.".colorize(:red)
    puts "---------------------------------------"
  end

  def print_maker_instructions
    puts "Your mission:"
    puts "Create a 4-digit secret code.".colorize(:green)
    puts "---------------------------------------"
    puts "START GAME"
    puts "---------------------------------------"
    print_colours
  end

  def print_breaker_instructions
    puts "Your mission:"
    puts "Decrypt the 4-digit sequence within 12 tries.".colorize(:red)
    puts "---------------------------------------"
    puts "To aid you in your mission, additional info for each guess will be provided in the form of key pegs:"
    print "\u25C9 ".colorize(:red)
    puts "RED PEG: Correct Colour + Correct Position"
    print "\u25C9 ".colorize(:white)
    puts "WHITE PEG: Correct Colour + Wrong Position"
    print "\u25CC "
    puts "EMPTY: No match found"
    puts "Note: The sequence of the provided feedback is shuffled."
    puts "---------------------------------------"
    puts "START GAME"
  end

  def print_colours
    print "Available colours:"
    @colours.each do |colour, symbol|
      print " #{symbol}".colorize(colour)
    end
    print "\n"
  end

  def print_answer
    print "Revealing the secret code:"
    @answer.each do |digit|
      @colours.each_with_index do |(colour, symbol), index|
        print " #{symbol}".colorize(colour) if index == digit.to_i - 1
      end
    end
    print "\n"
  end

  def assign_player_role
    loop do
      print "Choose your role - [1] or [2] : "
      @player_role = gets.chomp
      break if @player_role == "1" || @player_role == "2"

      puts "Invalid input: Please try again"
    end

    case @player_role
    when "1"
      @code_maker = HumanCodeMaker.new
      @code_breaker = ComputerCodeBreaker.new
      print_maker_instructions
    when "2"
      @code_maker = CodeMaker.new
      @code_breaker = CodeBreaker.new
      print_breaker_instructions
    end
  end

  def start_game
    print_instructions
    assign_player_role

    @answer = @code_maker.generate_code

    loop do
      @game_board.print_board
      guess = play_round
      if check_win?(guess)
        @game_board.print_board
        puts "Congratulations! The #{@code_breaker} has won the game!"
        break
      elsif @number_of_guesses == 12
        @game_board.print_board
        puts "The #{@code_breaker} has run out of guesses. The #{@code_maker} has won the game!"
        break
      end
    end

    print_answer
    puts "GAME OVER"
  end
end
